In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.11.0
atlas_3_10_blas_info:
  NOT AVAILABLE
blas_info:
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib']
atlas_blas_threads_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    language = c
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib']
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
lapack_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    language = c
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    library_dirs = ['/usr/lib']
blas_mkl_info:
  NOT AVAILABLE
lapack_info:
    language = f77
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib']
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
atlas_3_10_info:
  

In [4]:
#create a vector size 10
z3 = np.zeros(10)
print(z3)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    betw

In [7]:
z5 = np.zeros(10)
z5[5] = 1
print(z5)

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]


In [10]:
z6 = np.arange(10,50)
print(z6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
z6[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [13]:
z8 = np.arange(9).reshape((3,3))
print(z8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Find indices of non-zero elements from [1,2,0,0,4,0] 
np.nonzero( [1,2,0,0,4,0] )

(array([0, 1, 4]),)

In [17]:
#10 dentity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
np.random.random(27).reshape((3,3,3))
np.random.random((3,3,3))


array([[[ 0.58971176,  0.13302242,  0.95153271],
        [ 0.64173386,  0.62199705,  0.05887005],
        [ 0.12537419,  0.47577728,  0.52386174]],

       [[ 0.86345242,  0.21624035,  0.01727441],
        [ 0.13177434,  0.52423457,  0.59329499],
        [ 0.89163279,  0.87868782,  0.78132808]],

       [[ 0.48228911,  0.17080408,  0.40576196],
        [ 0.82079901,  0.35031382,  0.98080084],
        [ 0.83147311,  0.51562867,  0.42463389]]])

In [23]:
z12 = np.random.random((10,10))
print(z12.min())
print(z12.max())

0.00080255253348
0.997870180057


In [25]:
z13 = np.random.rand(30)
print(z13)
print(z13.mean())

[ 0.59252285  0.41455981  0.66908898  0.56920204  0.8175612   0.16442295
  0.42776617  0.31673887  0.89288968  0.47083616  0.78782735  0.64499195
  0.22598773  0.41901287  0.28771346  0.48611296  0.09272088  0.48086577
  0.50206534  0.56651094  0.88160079  0.19852339  0.80940499  0.29838721
  0.77879657  0.47953497  0.73110005  0.17028996  0.41189982  0.58678796]
0.505857455582


In [38]:
z14 = np.ones((10,10))
z14[1:9,1:9] = 0
z14

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [39]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [47]:
np.diag(np.arange(1,5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [77]:
z17 = np.arange(64)
z17 = z17.reshape(8,8)
z17[1::2,::2] = 0
z17[::2,1::2] = 0
z17

array([[ 0,  0,  2,  0,  4,  0,  6,  0],
       [ 0,  9,  0, 11,  0, 13,  0, 15],
       [16,  0, 18,  0, 20,  0, 22,  0],
       [ 0, 25,  0, 27,  0, 29,  0, 31],
       [32,  0, 34,  0, 36,  0, 38,  0],
       [ 0, 41,  0, 43,  0, 45,  0, 47],
       [48,  0, 50,  0, 52,  0, 54,  0],
       [ 0, 57,  0, 59,  0, 61,  0, 63]])

In [87]:
z18 = np.arange(1, 6*7*8 + 1)
z18 = z18.reshape(6,7,8)
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [101]:
np.tile([[1],[2], [3]],(4,4))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [105]:
z20 = np.arange(1,26).reshape(5,5)
zmax, zmin = z20.max(), z20.min()
z20 = (z20 - zmin)/(zmax - zmin)
z20

array([[ 0.        ,  0.04166667,  0.08333333,  0.125     ,  0.16666667],
       [ 0.20833333,  0.25      ,  0.29166667,  0.33333333,  0.375     ],
       [ 0.41666667,  0.45833333,  0.5       ,  0.54166667,  0.58333333],
       [ 0.625     ,  0.66666667,  0.70833333,  0.75      ,  0.79166667],
       [ 0.83333333,  0.875     ,  0.91666667,  0.95833333,  1.        ]])